image: gitpod/workspace-full

tasks:
  - name: Setup Environment
    init: |
      # 安装 Python 依赖
      pip install --upgrade pip
      pip install transformers datasets torch gradio huggingface_hub
    command: |
      echo "环境准备完成！"
      echo "你可以开始使用 Hugging Face 相关工具了"

ports:
  - port: 7860
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
